<a href="https://colab.research.google.com/github/mat87/big-data/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

np.__version__

A = np.array([1,2,3])
A.dtype

dtype('int64')

In [7]:

A = np.array([1.1,2,3])
A.dtype

dtype('float64')

In [9]:
A = np.array([1,2,3], dtype="float")
A.dtype
A

array([1., 2., 3.])

In [11]:
A = np.array([1.2,2.4,3.4], dtype="int")
A.dtype


dtype('int64')

In [16]:
np.zeros(shape=(4,10), dtype='uint8')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

1D Array

In [19]:
np.ones(shape=(5,7), dtype='uint8')

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [21]:
np.full(shape=(4,5), fill_value=45, dtype='int')

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [23]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [27]:
np.arange(start=100, stop=10, step=-0.1)

array([100. ,  99.9,  99.8,  99.7,  99.6,  99.5,  99.4,  99.3,  99.2,
        99.1,  99. ,  98.9,  98.8,  98.7,  98.6,  98.5,  98.4,  98.3,
        98.2,  98.1,  98. ,  97.9,  97.8,  97.7,  97.6,  97.5,  97.4,
        97.3,  97.2,  97.1,  97. ,  96.9,  96.8,  96.7,  96.6,  96.5,
        96.4,  96.3,  96.2,  96.1,  96. ,  95.9,  95.8,  95.7,  95.6,
        95.5,  95.4,  95.3,  95.2,  95.1,  95. ,  94.9,  94.8,  94.7,
        94.6,  94.5,  94.4,  94.3,  94.2,  94.1,  94. ,  93.9,  93.8,
        93.7,  93.6,  93.5,  93.4,  93.3,  93.2,  93.1,  93. ,  92.9,
        92.8,  92.7,  92.6,  92.5,  92.4,  92.3,  92.2,  92.1,  92. ,
        91.9,  91.8,  91.7,  91.6,  91.5,  91.4,  91.3,  91.2,  91.1,
        91. ,  90.9,  90.8,  90.7,  90.6,  90.5,  90.4,  90.3,  90.2,
        90.1,  90. ,  89.9,  89.8,  89.7,  89.6,  89.5,  89.4,  89.3,
        89.2,  89.1,  89. ,  88.9,  88.8,  88.7,  88.6,  88.5,  88.4,
        88.3,  88.2,  88.1,  88. ,  87.9,  87.8,  87.7,  87.6,  87.5,
        87.4,  87.3,

In [28]:
np.linspace(start=0, stop=1, num=341)

array([0.        , 0.00294118, 0.00588235, 0.00882353, 0.01176471,
       0.01470588, 0.01764706, 0.02058824, 0.02352941, 0.02647059,
       0.02941176, 0.03235294, 0.03529412, 0.03823529, 0.04117647,
       0.04411765, 0.04705882, 0.05      , 0.05294118, 0.05588235,
       0.05882353, 0.06176471, 0.06470588, 0.06764706, 0.07058824,
       0.07352941, 0.07647059, 0.07941176, 0.08235294, 0.08529412,
       0.08823529, 0.09117647, 0.09411765, 0.09705882, 0.1       ,
       0.10294118, 0.10588235, 0.10882353, 0.11176471, 0.11470588,
       0.11764706, 0.12058824, 0.12352941, 0.12647059, 0.12941176,
       0.13235294, 0.13529412, 0.13823529, 0.14117647, 0.14411765,
       0.14705882, 0.15      , 0.15294118, 0.15588235, 0.15882353,
       0.16176471, 0.16470588, 0.16764706, 0.17058824, 0.17352941,
       0.17647059, 0.17941176, 0.18235294, 0.18529412, 0.18823529,
       0.19117647, 0.19411765, 0.19705882, 0.2       , 0.20294118,
       0.20588235, 0.20882353, 0.21176471, 0.21470588, 0.21764

In [32]:
A = np.arange(15)
A
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
A = np.arange(15)
A
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
A = np.arange(15)
A
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])