<a href="https://colab.research.google.com/github/mat87/big-data/blob/master/liczby_pseudolosowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

In [ ]:
np.random.seed(0)

In [4]:
np.random.randn(10, 5)

array([[ 0.96214504, -0.85155053,  0.19127482,  0.01178696,  1.66128059],
       [-0.48932681, -1.03928894, -0.51029987, -0.11326431,  1.52924681],
       [ 0.90147681, -0.93878963, -1.02225442,  1.23030856,  0.61696142],
       [ 0.85235984, -0.84657127, -0.35356283,  2.4196409 ,  1.93051272],
       [ 1.32474858, -0.62760572, -0.15475701, -1.11796923, -1.06010009],
       [ 0.80368332, -1.0759016 , -1.77414768,  0.25643363, -0.08327985],
       [ 0.76539132, -0.54056288,  0.80434859, -1.97174331, -0.5030308 ],
       [ 0.31085809, -0.45625714, -0.58258585, -0.86726012, -1.43528804],
       [-1.38137183,  2.79099604,  0.63982786,  0.13794205, -1.7240277 ],
       [ 1.53040114,  0.61269739,  0.57331687,  0.3470848 ,  0.16322356]])

In [9]:
np.random.rand()

0.7886501966878394

In [11]:
np.random.rand(10,5)

array([[0.37334126, 0.39841244, 0.81960178, 0.77604333, 0.96571407],
       [0.8102068 , 0.85399407, 0.34231357, 0.88966531, 0.15348236],
       [0.10422385, 0.40075508, 0.11539893, 0.29437482, 0.63008128],
       [0.36878977, 0.61758144, 0.34224347, 0.98643453, 0.04281634],
       [0.47479053, 0.00670236, 0.79398775, 0.27994199, 0.77451019],
       [0.52893919, 0.78040267, 0.35390621, 0.04438812, 0.36349737],
       [0.08743961, 0.85776765, 0.52815305, 0.91398905, 0.4478951 ],
       [0.30200018, 0.56134695, 0.86049384, 0.32933182, 0.57937667],
       [0.58659217, 0.3189053 , 0.71005522, 0.08834515, 0.47017573],
       [0.07385261, 0.53465352, 0.92112471, 0.81982272, 0.29116157]])

In [12]:
np.random.randint(10)

3

In [22]:
np.random.choice([3,4,5,6,3,2])

3

In [24]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.random.shuffle(data)
data

array([9, 7, 5, 1, 3, 2, 6, 8, 0, 4])